version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network   
  products:
    build:
      context: ./products
    ports:
      - "3001:3001"
    networks:
      - my-network
  shopping-cart:
    build:
      context: ./shopping-cart
    ports:
      - "3002:3002"
    networks:
      - my-network

networks:
  my-network:

