version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.0
    image: frontend-app
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - products
      - shopping-cart   
  products:
    container_name: products
    build:
      context: ./products
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.0
    image: products-app
    ports:
      - "3001:3001"
    environment:
      - PRODUCTS_SERVICE=products
    hostname: products
    networks:
      - my-network
  shopping-cart:
    container_name: shopping-cart
    build:
      context: ./shopping-cart
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.0
    image: shopping-cart-app
    ports:
      - "3002:3002"
    environment:
      - SHOPPING_CART_SERVICE=shopping-cart
    hostname: shopping-cart
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
