version: '3'
networks:
  products-devops:
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PRODUCTS_SERVICE=http://products:3001
      - SHOPPING_CART_SERVICE=http://shopping-cart:3002
    networks:
      - products-devops
    depends_on:
      - products
      - shopping-cart

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - products-devops

  shopping-cart:
    build:
      context: ./shopping-cart
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - products-devops
