version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  product:
    build:
      context: ./product
    ports:
      - "3001:3001"
  shopping-cart:
    build:
      context: ./shopping-cart
    ports:
      - "3002:3002"
