apiversion: apps/v1
kind: Deployment
metadata:
 name: products-deploy
 labels: 
  app: products
spec: 
 selector:
  matchLabels:
   app: products
 template:
  metadata:
   labels:
    app: products
  spec:
   containers:
   - name: products 
     image: yirlli/ms-products:1.0
     ports:
     - containerPort: 3001:3001
