apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deploy
  labels:
    app: products
    version: v1
spec:
  selector:
    matchLabels:
      app: products
      version: v1
  template:
    metadata:
      labels:
        app: products
        version: v1
    spec:
      containers:
      - name: products
        image: yirlli/ms-products:1.0
        ports:
        - containerPort: 3001
